name: Publish current branch to npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        package: [
          .
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # fetch-depth 0 needed for NBGV
      - name: Use Node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: npm ci
      - run: cd ${{ matrix.package }}; npm run build
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v3
        id: npmtest
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          registry: https://registry.npmjs.org/
          tag: 'latest'
          access: public
          package: ${{ matrix.package }}
